### ISSUE TITLE
Orbit double arrow between Imipramin and Amitriptylin is rendered twice

### ISSUE THREAD

**Issue by ephaee** [epha/matrix#19]
Investigate why the double arrow between Imipramin and Amitriptylin is rendered 2 times

https://matrix.epha.ch/#/gtin:24041,37360,24041/

**Comment by curki** [comment]
Both IA (Levomepromazin - Amitriptylin, Lithium - Lisinopril) have been twice in matrix - double IA deleted

**Comment by ephaee** [comment]
fixed
