### ISSUE TITLE
do we need a github account for annika?

### ISSUE THREAD

**Issue by elmirafar** [epha/matrix#35]

**Comment by ephaee** [comment]
Definitely yes. Please let me know what her username is.

**Comment by elmirafar** [comment]
Her username ist:     Amjoy     (created last week)
Please tell me if you need her email-address. 
Welcome back to work ;-)

**Comment by elmirafar** [comment]
Her username ist:     Amjoy     (created last week)
Please tell me if you need her email-address. 
Welcome back to work ;-)
