### ISSUE TITLE
URL for interactions

### ISSUE THREAD

**Issue by kappisj** [epha/matrix#36]
Hi there, 

we are linking your interaction service from within our EMR 'Elexis'. We are using the following URL (with changing EAN numbers) to request the information needed:

http://matrix.epha.ch/#7680569610181,7680390530474,7680546530426,7680529041024

unfortunately this link will bring me to https://matrix.epha.ch/ without showing me any results. Could you tell me, in which way you need the URL to get results like https://matrix.epha.ch/#/gtin:43838,19395/

Do we just have to add the 'gtin:' prefix? Thank you for a quick response. 

best wishes, 
Julian
Medelexis AG

**Comment by Jonas74** [comment]
Please change
http://matrix.epha.ch/#7680569610181,7680390530474,7680546530426,7680529041024 to
https://matrix.epha.ch/#/7680569610181,7680390530474,7680546530426,7680529041024 or (better)
https://matrix.epha.ch/#/gtin:7680569610181,7680390530474,7680546530426,7680529041024

Two products have been deregistered at swissmedic. To get current list of products you can use github.com/epha/download .We are working on the support of deregistered products in the future (https://github.com/epha/download/issues/13).

If you want to hide the navigation, add "/mode:headless" to the hash.
