### ISSUE TITLE
PDF print out of order

### ISSUE THREAD

**Issue by curki** [epha/matrix#38]
@ephaee: PDF für Interaktionen mit Acetylsalicylsäure (Beispiel Aspirin cardio und Novalgin, Aspirin cardio und Methotrexat) lassen sich nicht öffnen. Bitte schnellstmöglich reparieren.

**Comment by ephaee** [comment]
Test:
https://matrix.epha.ch/#/gtin:16950,51795/
PDF
https://data.epha.ch/matrix/M000499/Metamizol-Natrium-Acetylsalicyls%C3%A4ure.pdf

**Comment by ephaee** [comment]
PDF will change to
https://data.epha.ch/matrix/IA000499/Metamizol-Natrium-Acetylsalicyls%C3%A4ure.pdf

**Comment by curki** [comment]
also bisher klappts  bei mir noch nicht mit dem PDF..
Ich bräuchte die PDFs bis morgen (ASS cardio - Novalgin, ASS Cardio - Methotrexat). Es ist für ein Projekt.
Wird das klappen?

Am 16.02.2015 um 19:33 schrieb Enrique Erne <notifications@github.com>:

**Comment by ephaee** [comment]
Ja der Issue ist auch noch offen. Wir werde heute Matrix neu releasen und deployen... (wenn @Jonas74  zurück ist) das Problem ist momentan Substanzen mit "Spezialzeichen" (äüö und -) im Namen.
