### ISSUE TITLE
Inconsistency: Metamizol-Natrium beeinflusst Acetylsalicylsäure

### ISSUE THREAD

**Issue by ephaee** [epha/matrix#40]
This seems wrong please check:

https://matrix.epha.ch/#/gtin:16950,51795/ (IA and 8 alternatives)
versus
https://matrix.epha.ch/#/gtin:08537,14746/ (NO IA and 2 alternatives)

**Comment by ephaee** [comment]
There are different ATC's for Acetylsalicylsäure
N02BA01 and B01AC06
N02BA01 contains Apsirin, Alka-Seltzer and a few more
B01AC06 contains Aspirin Cardio, Titral 100 SR and some others

**Comment by ephaee** [comment]
Seems as N02BA01 and B01AC06 are incosistent(?) on http://www.swissmedicinfo.ch as well

**Comment by Jonas74** [comment]
No, this is correct. ATC groups according to substance and indication. IA are correct.
