### ISSUE TITLE
bi info missing in database?

### ISSUE THREAD

**Issue by ephaee** [epha/matrix#5]
We are going to support bi directional interactions (double sided arrows), but have an issue between Amitriptylin and Levomepromazin. Could somebody confirm if this information is missing in the database?

https://matrix.epha.ch/#/37360,24041
http://localhost:8888/matrix/#/gtin:37360,24041/

**Comment by curki** [comment]
Amitriptylin - Levomepromazin already fixed
Imipramin - Amitriptylin not reproducable (has probably altready been fixed?)

**Comment by ephaee** [comment]
Fixed https://matrix.epha.ch/#/gtins=37360,24041/
