### ISSUE TITLE
wrong alternatives

### ISSUE THREAD

**Issue by curki** [epha/matrix#58]
https://matrix.epha.ch/#/gtin:54752,54752,47596,50227,10368,53810,52189,41547,51078/

![24-03-2015 15-28-41](https://cloud.githubusercontent.com/assets/5794379/6804235/e72f6322-d23c-11e4-88f5-9d551a0b172d.png)

**Comment by ephaee** [comment]
fixed please test

**Comment by curki** [comment]
ok. no wrong alternatives detectable.

**Comment by ephaee** [comment]
Thanks
