### ISSUE TITLE
Alternative missing and miselading alternative

### ISSUE THREAD

**Issue by curki** [epha/matrix#61]
https://matrix.epha.ch/#/gtin:57203,60530,62903,62684,61549,47344,50469,55649,61389,62956/

Alternatives for Ticagrelor: Prasugrel missing and "Kombinationen" ist misleading, no valuable information

**Comment by ephaee** [comment]
Opended an issue a while ago to document the problem with Verschiedene, Verschiedene Kombinationen and Kombinationen see https://github.com/epha/expert/issues/4

**Comment by curki** [comment]
related https://github.com/epha/robot/issues/9

**Comment by ephaee** [comment]
Prasugrel is showing now
