### ISSUE TITLE
Again: wrong number of alternatives

### ISSUE THREAD

**Issue by curki** [epha/matrix#62]
https://matrix.epha.ch/#/gtin:62903/

2 shown als number of alternatives, but no alternatives existing

**Comment by ephaee** [comment]
Can not reproduce maybe jonas fixed it already?

![matrix-alternatives](https://cloud.githubusercontent.com/assets/5112286/7075980/56f39400-df06-11e4-8771-706a2c8612ff.png)

**Comment by ephaee** [comment]
produkte is coming now from download.epha.ch see https://github.com/epha/matrix/issues/56
