### ISSUE TITLE
Kalium interactions not shown

### ISSUE THREAD

**Issue by curki** [epha/matrix#70]
https://matrix.epha.ch/#/gtin:57383,36360,21278,51434,35756/

KCL retard Drg Zulassungsnummer 35756, A12BA01
Kalium Hausmann KCL retad Drg Zulassungsnummer 36360, A12BA01
Kalium chrloatum 15% sintetica Zulassungsnummer 51434, B05XA01

not shown in matrix despite correct ATC Codes according to swissmedic file

**Comment by ephaee** [comment]
For some reason the arrow is rendered 3 times

![screen shot 2015-04-27 at 09 11 41](https://cloud.githubusercontent.com/assets/5112286/7343110/7bba2c30-ecbd-11e4-9a04-6bb4ad8acc72.png)

**Comment by ephaee** [comment]
Should be fixed. Please check and close

**Comment by curki** [comment]
Yes, fixed. It works!!
