### ISSUE TITLE
Tirosint, Phenhydan, Colestide

### ISSUE THREAD

**Issue by zdavatz** [epha/matrix#72]
Ein Hausarzt meldet, dass in der FI von Tirosint die folgenden Interaktionen vorkommen:

Tirosint interagiert mit: Phenhydan, Colestide

http://ch.oddb.org/de/gcc/fachinfo/reg/57455/chapter/interactions

Gruss
Zeno

**Comment by ephaee** [comment]
@amjoy can we close this issue ?
https://matrix.epha.ch/#/view=document/gtins=40855,39932,57455/

**Comment by zdavatz** [comment]
Ich kann die folgende Interaktion in den CSV Daten nicht finden:

/N03AB02.*H03AA01

also Phenytoin und Tirosint. Im Web-Interface von EPha wird sie oben aber angezeigt.

**Comment by zdavatz** [comment]
Wann kommen die neue Daten im CSV Export?
