### ISSUE TITLE
Wrong product / interaction shown

### ISSUE THREAD

**Issue by curki** [epha/matrix#73]
https://matrix.epha.ch/#/gtin:62392,49826/
In matrix an interaction between Gincosan and Sildenafil is shown, which is wrong. But, if you look at the details an interaction between "Moexipril and Diuretika (ATCC09BA13) and Sildenafil" is meant. 

In Swissmedic Gincosan has the ATC "A13", usually N06DX02 is the code for Ginkgo-preparations
zulassung": "49826",
      "sequenz": "1",
      "name": "Gincosan, capsule",
      "hersteller": "Ginsana SA",
      "itnummer": "02.97.0.",
      "atc": "A13",
      "heilmittelcode": "Phytotherapeutika",
      "erstzulassung": "30.1.1989",
      "zulassungsdatum": "30.1.1989",
      "gueltigkeitsdatum": "22.12.2018",
      "verpackung": "028",

Can anyone help me with this issue???

**Comment by Jonas74** [comment]
I corrected it by fixing the swissmedic atc. But question remains, why did it an interaction.

**Comment by ephaee** [comment]
The regex in getRelationSync matched shorter ATC that have the same ending as some other IA's

![screen shot 2015-05-04 at 16 22 11](https://cloud.githubusercontent.com/assets/5112286/7455109/e23b77a4-f279-11e4-9361-a6681e51957a.png)
